In [1]:
# from svnds.synphot import load_catalog
from svnds.synphot import Syn7DS, merge_tbl
import numpy as np

import os

<div class="alert alert-block alert-warning"> 'EL-COSMOS' data should be downloaded before running this notebook </div>

* Download [EL-COSMOS](https://cesam.lam.fr/aspic/files/elcosmos/readme_elcosmos.html)
* We assume the EL-COSMOS is structured as follows:
    - `path_elcomos`
        - `EL_COMOS_zone{n}.csv` is saved in the path where n = 1-9.

In [6]:
# PATH where EL-COSMOS data is located
# path_elcosmos = '/home/ehko/photz_for_7ds/test/test_data/elcosmos/'
path_elcosmos = '/data8/EL_COSMOS/elcosmos/'

# PATH to save output data
# path_save = '/home/ehko/photz_for_7ds/test/test_data/output/'
path_save = '/data8/EL_COSMOS/synphots/SDS/scale_18_eff/'

In [7]:
Tsamps = np.array([180, 180 * 364/14, 180 * 364/14 * 3, 180 * 364/14 * 5, 180 * 364/14 * 7, 180 * 365, 180 * 365 * 5], dtype = int)
print(Tsamps)

Tsamps = (Tsamps * 0.5).astype(int)
print(Tsamps)

[   180   4680  14040  23400  32760  65700 328500]
[    90   2340   7020  11700  16380  32850 164250]


In [8]:
syn = Syn7DS(path_elcosmos, path_save, Tsamps)

survey: 7DS
Exposure time: 
[    90   2340   7020  11700  16380  32850 164250]


In [9]:
syn.synphot(zones = range(1, 10), magscale = True, mag_ref = 18)

  0%|          | 129/60172 [00:06<51:11, 19.55it/s]

In [12]:
merge_tbl(path_save, "synphot_7DS_total.csv")

Final table is created
