In [1]:
# from svnds.synphot import load_catalog
from svnds.synphot import Syn7DS, merge_tbl
import numpy as np

import os

<div class="alert alert-block alert-warning"> 'EL-COSMOS' data should be downloaded before running this notebook </div>

* Download [EL-COSMOS](https://cesam.lam.fr/aspic/files/elcosmos/readme_elcosmos.html)
* We assume the EL-COSMOS is structured as follows:
    - `path_elcomos`
        - `EL_COMOS_zone{n}.csv` is saved in the path where n = 1-9.

In [2]:
# PATH where EL-COSMOS data is located
# path_elcosmos = '/home/ehko/photz_for_7ds/test/test_data/elcosmos/'
path_elcosmos = '/data8/EL_COSMOS/elcosmos/'

# PATH to save output data
# path_save = '/home/ehko/photz_for_7ds/test/test_data/output/'
path_save = '/data8/EL_COSMOS/synphots/SDS/scale_19p5_eff/'

In [3]:
Tsamps = np.array([180, 180 * 364/14, 180 * 364/14 * 3, 180 * 364/14 * 5, 180 * 364/14 * 7, 180 * 365, 180 * 365 * 5], dtype = int)
print(Tsamps)

Tsamps = (Tsamps * 0.5).astype(int)
print(Tsamps)

[   180   4680  14040  23400  32760  65700 328500]
[    90   2340   7020  11700  16380  32850 164250]


In [4]:
syn = Syn7DS(path_elcosmos, path_save, Tsamps)

survey: 7DS
Exposure time: 
[    90   2340   7020  11700  16380  32850 164250]


In [6]:
syn.synphot(zones = [1, 2, 3, 4, 5, 6, 8, 9], magscale = True, mag_ref = 19.5)

100%|██████████| 60172/60172 [51:47<00:00, 19.36it/s]


zone 1 completed!


100%|██████████| 60892/60892 [52:51<00:00, 19.20it/s] 


zone 2 completed!


100%|██████████| 56967/56967 [49:26<00:00, 19.21it/s]


zone 3 completed!


100%|██████████| 57947/57947 [50:28<00:00, 19.13it/s]


zone 4 completed!


100%|██████████| 66143/66143 [57:29<00:00, 19.17it/s] 


zone 5 completed!


100%|██████████| 61524/61524 [53:20<00:00, 19.22it/s] 


zone 6 completed!


100%|██████████| 59354/59354 [51:36<00:00, 19.17it/s]


zone 8 completed!


100%|██████████| 60409/60409 [52:31<00:00, 19.17it/s] 


zone 9 completed!


In [8]:
merge_tbl(path_save, f"synphot_7DS_scale_{19.5:.1f}_yrs_all_eff_tot.csv")

Final table is created
